local config = require("lapis.config")
config("development", function()
  port(8080)
  return measure_performance(true)
end)
config("production", function()
  port(80)
  num_workers(4)
  code_cache("on")
  measure_performance(true)
  return cache_ttl(10)
end)
config("test", function()
  port(8081)
  return measure_performance(true)
end)
config("db_development", function()
  url("http://172.31.0.6:8529/")
  name("cms")
  login("root")
  return pass("password")
end)
config("db_production", function()
  url("http://172.31.0.6:8529/")
  name("cms")
  login("root")
  return pass("password")
end)
return config("db_127", function()
  url("http://172.31.0.6:8529/")
  name("cms")
  login("root")
  return pass("password")
end)
